// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job_JobType int32

const (
	Job_DEFAULT  Job_JobType = 0
	Job_FEATURED Job_JobType = 1
	Job_PREMIUM  Job_JobType = 2
)

var Job_JobType_name = map[int32]string{
	0: "DEFAULT",
	1: "FEATURED",
	2: "PREMIUM",
}

var Job_JobType_value = map[string]int32{
	"DEFAULT":  0,
	"FEATURED": 1,
	"PREMIUM":  2,
}

func (x Job_JobType) String() string {
	return proto.EnumName(Job_JobType_name, int32(x))
}

func (Job_JobType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2, 0}
}

type Job_JobStatus int32

const (
	Job_ACTIVE  Job_JobStatus = 0
	Job_HOLD    Job_JobStatus = 1
	Job_EXPIRED Job_JobStatus = 2
	Job_CLOSED  Job_JobStatus = 3
	Job_URGENT  Job_JobStatus = 4
)

var Job_JobStatus_name = map[int32]string{
	0: "ACTIVE",
	1: "HOLD",
	2: "EXPIRED",
	3: "CLOSED",
	4: "URGENT",
}

var Job_JobStatus_value = map[string]int32{
	"ACTIVE":  0,
	"HOLD":    1,
	"EXPIRED": 2,
	"CLOSED":  3,
	"URGENT":  4,
}

func (x Job_JobStatus) String() string {
	return proto.EnumName(Job_JobStatus_name, int32(x))
}

func (Job_JobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2, 1}
}

type Sallary struct {
	Value                uint64   `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sallary) Reset()         { *m = Sallary{} }
func (m *Sallary) String() string { return proto.CompactTextString(m) }
func (*Sallary) ProtoMessage()    {}
func (*Sallary) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *Sallary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sallary.Unmarshal(m, b)
}
func (m *Sallary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sallary.Marshal(b, m, deterministic)
}
func (m *Sallary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sallary.Merge(m, src)
}
func (m *Sallary) XXX_Size() int {
	return xxx_messageInfo_Sallary.Size(m)
}
func (m *Sallary) XXX_DiscardUnknown() {
	xxx_messageInfo_Sallary.DiscardUnknown(m)
}

var xxx_messageInfo_Sallary proto.InternalMessageInfo

func (m *Sallary) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Sallary) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type Attachment struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attachment) Reset()         { *m = Attachment{} }
func (m *Attachment) String() string { return proto.CompactTextString(m) }
func (*Attachment) ProtoMessage()    {}
func (*Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *Attachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attachment.Unmarshal(m, b)
}
func (m *Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attachment.Marshal(b, m, deterministic)
}
func (m *Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attachment.Merge(m, src)
}
func (m *Attachment) XXX_Size() int {
	return xxx_messageInfo_Attachment.Size(m)
}
func (m *Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_Attachment proto.InternalMessageInfo

func (m *Attachment) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Attachment) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Job struct {
	JobId                string        `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName              string        `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobDescription       string        `protobuf:"bytes,3,opt,name=job_description,json=jobDescription,proto3" json:"job_description,omitempty"`
	JobTag               string        `protobuf:"bytes,4,opt,name=job_tag,json=jobTag,proto3" json:"job_tag,omitempty"`
	JobCategory          string        `protobuf:"bytes,5,opt,name=job_category,json=jobCategory,proto3" json:"job_category,omitempty"`
	Location             string        `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Views                int64         `protobuf:"varint,7,opt,name=views,proto3" json:"views,omitempty"`
	SkillsRequired       []string      `protobuf:"bytes,8,rep,name=skills_required,json=skillsRequired,proto3" json:"skills_required,omitempty"`
	UsersApplied         []string      `protobuf:"bytes,9,rep,name=users_applied,json=usersApplied,proto3" json:"users_applied,omitempty"`
	JobType              Job_JobType   `protobuf:"varint,10,opt,name=job_type,json=jobType,proto3,enum=job.Job_JobType" json:"job_type,omitempty"`
	JobStatus            Job_JobStatus `protobuf:"varint,11,opt,name=job_status,json=jobStatus,proto3,enum=job.Job_JobStatus" json:"job_status,omitempty"`
	MinSallary           *Sallary      `protobuf:"bytes,12,opt,name=min_sallary,json=minSallary,proto3" json:"min_sallary,omitempty"`
	MaxSallary           *Sallary      `protobuf:"bytes,13,opt,name=max_sallary,json=maxSallary,proto3" json:"max_sallary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *Job) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *Job) GetJobDescription() string {
	if m != nil {
		return m.JobDescription
	}
	return ""
}

func (m *Job) GetJobTag() string {
	if m != nil {
		return m.JobTag
	}
	return ""
}

func (m *Job) GetJobCategory() string {
	if m != nil {
		return m.JobCategory
	}
	return ""
}

func (m *Job) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Job) GetViews() int64 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *Job) GetSkillsRequired() []string {
	if m != nil {
		return m.SkillsRequired
	}
	return nil
}

func (m *Job) GetUsersApplied() []string {
	if m != nil {
		return m.UsersApplied
	}
	return nil
}

func (m *Job) GetJobType() Job_JobType {
	if m != nil {
		return m.JobType
	}
	return Job_DEFAULT
}

func (m *Job) GetJobStatus() Job_JobStatus {
	if m != nil {
		return m.JobStatus
	}
	return Job_ACTIVE
}

func (m *Job) GetMinSallary() *Sallary {
	if m != nil {
		return m.MinSallary
	}
	return nil
}

func (m *Job) GetMaxSallary() *Sallary {
	if m != nil {
		return m.MaxSallary
	}
	return nil
}

func init() {
	proto.RegisterEnum("job.Job_JobType", Job_JobType_name, Job_JobType_value)
	proto.RegisterEnum("job.Job_JobStatus", Job_JobStatus_name, Job_JobStatus_value)
	proto.RegisterType((*Sallary)(nil), "job.Sallary")
	proto.RegisterType((*Attachment)(nil), "job.Attachment")
	proto.RegisterType((*Job)(nil), "job.Job")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xeb, 0x7c, 0x3a, 0x93, 0x34, 0xb5, 0x56, 0x95, 0x70, 0x7b, 0x80, 0x10, 0x0e, 0x18,
	0x41, 0x62, 0x35, 0x88, 0x4b, 0x11, 0x48, 0x69, 0xe2, 0x42, 0xaa, 0x7e, 0xc9, 0x4d, 0x10, 0xe2,
	0x12, 0xad, 0x9d, 0xad, 0x6b, 0x63, 0x7b, 0xcd, 0xda, 0x2e, 0xcd, 0x73, 0xf0, 0x34, 0xed, 0x89,
	0x77, 0xe1, 0x45, 0xd0, 0xee, 0x3a, 0x69, 0x0e, 0x88, 0x43, 0xa2, 0xf9, 0xcf, 0xfc, 0xfe, 0x93,
	0xd1, 0x64, 0x16, 0x9a, 0x11, 0x5d, 0x90, 0xb0, 0x9f, 0x30, 0x9a, 0x51, 0x54, 0x0e, 0xa8, 0xb3,
	0x7f, 0xe8, 0xf9, 0xd9, 0x4d, 0xee, 0xf4, 0x5d, 0x1a, 0x99, 0x7e, 0x7c, 0x4d, 0x9d, 0x90, 0xde,
	0xd1, 0x84, 0xc4, 0xa6, 0x60, 0xdc, 0x9e, 0x47, 0xe2, 0x9e, 0x47, 0x59, 0x64, 0xd2, 0x24, 0xf3,
	0x69, 0x9c, 0x9a, 0x5c, 0xc8, 0x06, 0xfb, 0xbd, 0x0d, 0xaf, 0x47, 0x3d, 0x2a, 0x3d, 0x4e, 0x7e,
	0x2d, 0x94, 0x10, 0x22, 0x92, 0x78, 0x77, 0x04, 0xf5, 0x2b, 0x1c, 0x86, 0x98, 0x2d, 0xd1, 0x2e,
	0x54, 0x6f, 0x71, 0x98, 0x13, 0x5d, 0xe9, 0x28, 0x46, 0xcd, 0x96, 0x02, 0xed, 0x83, 0xea, 0xe6,
	0x8c, 0x91, 0xd8, 0x5d, 0xea, 0xa5, 0x8e, 0x62, 0x34, 0xec, 0xb5, 0x3e, 0xac, 0x3d, 0xdc, 0xef,
	0x95, 0x54, 0xa5, 0xfb, 0x11, 0x60, 0x98, 0x65, 0xd8, 0xbd, 0x89, 0x48, 0x9c, 0x21, 0x04, 0x95,
	0x6c, 0x99, 0xc8, 0x36, 0x0d, 0x5b, 0xc4, 0x8f, 0xbd, 0x65, 0x0b, 0x29, 0xd6, 0xfe, 0x5f, 0x55,
	0x28, 0x9f, 0x50, 0x07, 0x3d, 0x83, 0x5a, 0x40, 0x9d, 0xb9, 0xbf, 0x90, 0xde, 0x23, 0xf5, 0xe1,
	0x7e, 0xaf, 0x02, 0x25, 0x43, 0xb1, 0xab, 0x01, 0x75, 0x26, 0x0b, 0x64, 0x82, 0xca, 0x81, 0x18,
	0x47, 0x45, 0xa7, 0xa3, 0xdd, 0x87, 0xfb, 0x3d, 0x0d, 0xda, 0xa8, 0x75, 0x8b, 0x99, 0x7b, 0x83,
	0x99, 0xf1, 0xee, 0x60, 0xf0, 0xca, 0xae, 0x07, 0xd4, 0x39, 0xc7, 0x11, 0x41, 0x1f, 0x60, 0x87,
	0x1b, 0x16, 0x24, 0x75, 0x99, 0x2f, 0x96, 0xa5, 0x97, 0xff, 0xe3, 0x6b, 0x07, 0xd4, 0x19, 0x3f,
	0xb2, 0xe8, 0x09, 0xf0, 0x4e, 0xf3, 0x0c, 0x7b, 0x7a, 0x45, 0x0c, 0xce, 0xe7, 0x9b, 0x62, 0x0f,
	0x3d, 0x87, 0x16, 0x2f, 0xb8, 0x38, 0x23, 0x1e, 0x65, 0x4b, 0xbd, 0x2a, 0xaa, 0xcd, 0x80, 0x3a,
	0xa3, 0x22, 0xc5, 0x17, 0x17, 0x52, 0x17, 0x8b, 0xdf, 0xac, 0xc9, 0xc5, 0xad, 0xb4, 0x58, 0x87,
	0x4f, 0x7e, 0xa6, 0x7a, 0xbd, 0xa3, 0x18, 0x65, 0x5b, 0x0a, 0xf4, 0x12, 0x76, 0xd2, 0xef, 0x7e,
	0x18, 0xa6, 0x73, 0x46, 0x7e, 0xe4, 0x3e, 0x23, 0x0b, 0x5d, 0xed, 0x94, 0x8d, 0x86, 0xdd, 0x96,
	0x69, 0xbb, 0xc8, 0xa2, 0x17, 0xb0, 0x9d, 0xa7, 0x84, 0xa5, 0x73, 0x9c, 0x24, 0xa1, 0x4f, 0x16,
	0x7a, 0x43, 0x60, 0x2d, 0x91, 0x1c, 0xca, 0x1c, 0x7a, 0x2d, 0x77, 0x25, 0xfe, 0x0a, 0xe8, 0x28,
	0x46, 0x7b, 0xa0, 0xf5, 0x03, 0xea, 0xf4, 0x4f, 0xe4, 0x67, 0xba, 0x4c, 0x88, 0xd8, 0x13, 0x0f,
	0xd0, 0x01, 0x00, 0x87, 0xd3, 0x0c, 0x67, 0x79, 0xaa, 0x37, 0x05, 0x8e, 0x36, 0xf1, 0x2b, 0x51,
	0xb1, 0x1b, 0xc1, 0x2a, 0x44, 0x3d, 0x68, 0x46, 0x7e, 0x3c, 0x4f, 0xe5, 0xf5, 0xe8, 0xad, 0x8e,
	0x62, 0x34, 0x07, 0x2d, 0xe1, 0x29, 0x2e, 0xca, 0x86, 0xc8, 0x8f, 0x57, 0xd7, 0xc5, 0x71, 0x7c,
	0xb7, 0xc6, 0xb7, 0xff, 0x89, 0xe3, 0xbb, 0x22, 0xee, 0x1e, 0x40, 0xbd, 0x18, 0x12, 0x35, 0xa1,
	0x3e, 0xb6, 0x8e, 0x87, 0xb3, 0xd3, 0xa9, 0xb6, 0x85, 0x5a, 0xa0, 0x1e, 0x5b, 0xc3, 0xe9, 0xcc,
	0xb6, 0xc6, 0x9a, 0xc2, 0x4b, 0x97, 0xb6, 0x75, 0x36, 0x99, 0x9d, 0x69, 0xa5, 0xee, 0x31, 0x34,
	0xd6, 0x83, 0x22, 0x80, 0xda, 0x70, 0x34, 0x9d, 0x7c, 0xb1, 0xb4, 0x2d, 0xa4, 0x42, 0xe5, 0xf3,
	0xc5, 0x69, 0xc1, 0x5b, 0x5f, 0x2f, 0x27, 0xdc, 0x5c, 0xe2, 0xc8, 0xe8, 0xf4, 0xe2, 0xca, 0x1a,
	0x6b, 0x65, 0x1e, 0xcf, 0xec, 0x4f, 0xd6, 0xf9, 0x54, 0xab, 0xac, 0xae, 0xf2, 0x68, 0xf0, 0xfb,
	0xcf, 0x53, 0xe5, 0xdb, 0x9b, 0x8d, 0xf7, 0x14, 0xfb, 0x0c, 0x07, 0x1e, 0xa1, 0xcc, 0xf3, 0x71,
	0x6c, 0x06, 0xd4, 0x31, 0x53, 0xe6, 0x9a, 0xe2, 0xf9, 0xbe, 0x17, 0xdf, 0x4e, 0x4d, 0xbc, 0xaa,
	0xb7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x17, 0xa4, 0x81, 0xd8, 0xd4, 0x03, 0x00, 0x00,
}
