apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-deployment
  labels:
    app: job
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
        - name: job
          image: nirajgeorgian/job:latest
          imagePullPolicy: "Always"
          ports:
            - name: job-service
              containerPort: 3000
          env:
            - name: DATABASEURI
              value: "host=salt.db.elephantsql.com user=pvhdolsp dbname=pvhdolsp password=WPSXt41F15pPgpTx-0V7CC6Ec5ALoyvL sslmode=disable"
            - name: PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  selector:
    app: job
  ports:
    - port: 3000
      targetPort: job-service
